//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class WebShop_Cart
{
    public int Id { get; set; }
    public string ClientId { get; set; }
    public int ProductId { get; set; }
    public int Amount { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public bool IsInChart { get; set; }

    public virtual WebShop_Products WebShop_Products { get; set; }
}

public partial class WebShop_Products
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WebShop_Products()
    {
        this.WebShop_Cart = new HashSet<WebShop_Cart>();
    }

    public int Id { get; set; }
    public int TypeId { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> Price { get; set; }
    public string Description { get; set; }
    public string Image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WebShop_Cart> WebShop_Cart { get; set; }
    public virtual WebShop_ProductTypes WebShop_ProductTypes { get; set; }
}

public partial class WebShop_ProductTypes
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WebShop_ProductTypes()
    {
        this.WebShop_Products = new HashSet<WebShop_Products>();
    }

    public int Id { get; set; }
    public string TypeName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WebShop_Products> WebShop_Products { get; set; }
}

public partial class WebShop_UserInformation
{
    public int Id { get; set; }
    public string GUID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
}
